/*
 * DCFB API
 * API spec for DCFB API.
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package fi.metatavu.dcfb.client;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Gets or Sets ItemListSort
 */
public enum ItemListSort {
  
  CREATED_AT_DESC("CREATED_AT_DESC"),
  
  CREATED_AT_ASC("CREATED_AT_ASC"),
  
  MODIFIED_AT_DESC("MODIFIED_AT_DESC"),
  
  MODIFIED_AT_ASC("MODIFIED_AT_ASC"),
  
  SCORE_DESC("SCORE_DESC"),
  
  SCORE_ASC("SCORE_ASC");

  private String value;

  ItemListSort(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static ItemListSort fromValue(String text) {
    for (ItemListSort b : ItemListSort.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }
}

